name: Terraform Deploy
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: aws-actions

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Plan
        env:
          AMI_ID: ${{ secrets.AMI_ID }}
          VPC_ID: ${{ secrets.VPC_ID }}
          SG_ID: ${{ secrets.SECURITY_GROUP_ID }}
          INSTANCE_PROFILE_NAME: ${{ secrets.INSTANCE_PROFILE_NAME }}
          SN_1: ${{ secrets.SUBNET_1 }}
          SN_2: ${{ secrets.SUBNET_2 }}
        run: |
          terraform plan \
            -var="ami_id=$AMI_ID" \
            -var="vpc_id=$VPC_ID" \
            -var="security_group_id=$SG_ID" \
            -var="instance_profile_name=$INSTANCE_PROFILE_NAME" \
            -var="subnet_ids=[\"$SN_1\",\"$SN_2\"]"

      - name: Terraform Apply
        env:
          AMI_ID: ${{ secrets.AMI_ID }}
          VPC_ID: ${{ secrets.VPC_ID }}
          SG_ID: ${{ secrets.SECURITY_GROUP_ID }}
          INSTANCE_PROFILE_NAME: ${{ secrets.INSTANCE_PROFILE_NAME }}
          SN_1: ${{ secrets.SUBNET_1 }}
          SN_2: ${{ secrets.SUBNET_2 }}
        run: |
          terraform apply -auto-approve \
            -var="ami_id=$AMI_ID" \
            -var="vpc_id=$VPC_ID" \
            -var="security_group_id=$SG_ID" \
            -var="instance_profile_name=$INSTANCE_PROFILE_NAME" \
            -var="subnet_ids=[\"$SN_1\",\"$SN_2\"]"

      - name: Terraform Output
        id: tf_output
        run: |
          ALB_URL=$(terraform output -raw alb_dns_name)
          echo "ALB_URL=$ALB_URL" >> $GITHUB_ENV

      - name: Show AWS Region
        run: echo "AWS_REGION=${{ secrets.AWS_REGION }}"
      
      - name: Health Check
        run: |
          echo "Testing Load Balancer at http://${{ env.ALB_URL }}"
          curl -Is http://${{ env.ALB_URL }} | head -n 1
        