name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type YES to confirm destroy'
        required: true
        default: 'NO'

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    if: github.event.inputs.confirm_destroy == 'YES'
    runs-on: ubuntu-latest
    environment: aws-actions

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Destroy
        env:
          AMI_ID: ${{ secrets.AMI_ID }}
          VPC_ID: ${{ secrets.VPC_ID }}
          SG_ID: ${{ secrets.SG_ID }}
          INSTANCE_PROFILE_NAME: ${{ secrets.INSTANCE_PROFILE_NAME }}
          SN_1: ${{ secrets.SN_1 }}
          SN_2: ${{ secrets.SN_2 }}
        run: |
          terraform destroy -auto-approve \
            -var="ami_id=$AMI_ID" \
            -var="vpc_id=$VPC_ID" \
            -var="security_group_id=$SG_ID" \
            -var="instance_profile_name=$INSTANCE_PROFILE_NAME" \
            -var='subnet_ids=["'"$SN_1"'","'"$SN_2"'"]'
